//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34011
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _247.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_247.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a about.
        /// </summary>
        public static string AboutMenuItemText {
            get {
                return ResourceManager.GetString("AboutMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string AboutPageCopyrightText {
            get {
                return ResourceManager.GetString("AboutPageCopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 24/7 application is a Sunshine aplication using of the Nokia map component of Windows Phone 8..
        /// </summary>
        public static string AboutPageDescriptionText {
            get {
                return ResourceManager.GetString("AboutPageDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a www.sunshinelab.com.
        /// </summary>
        public static string AboutPageDeveloperUrl {
            get {
                return ResourceManager.GetString("AboutPageDeveloperUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Learn more at .
        /// </summary>
        public static string AboutPageLearnMoreText {
            get {
                return ResourceManager.GetString("AboutPageLearnMoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a about.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version: .
        /// </summary>
        public static string AboutPageVersionText {
            get {
                return ResourceManager.GetString("AboutPageVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu Item.
        /// </summary>
        public static string AppBarMenuItemText1 {
            get {
                return ResourceManager.GetString("AppBarMenuItemText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 24/7.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MAP EXPLORER.
        /// </summary>
        public static string ApplicationTitle1 {
            get {
                return ResourceManager.GetString("ApplicationTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a calculating route....
        /// </summary>
        public static string CalculatingRouteProgressText {
            get {
                return ResourceManager.GetString("CalculatingRouteProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dark color mode.
        /// </summary>
        public static string ColorModeDarkMenuItemText {
            get {
                return ResourceManager.GetString("ColorModeDarkMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a light color mode.
        /// </summary>
        public static string ColorModeLightMenuItemText {
            get {
                return ResourceManager.GetString("ColorModeLightMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a directions off.
        /// </summary>
        public static string DirectionsOffMenuItemText {
            get {
                return ResourceManager.GetString("DirectionsOffMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a directions on.
        /// </summary>
        public static string DirectionsOnMenuItemText {
            get {
                return ResourceManager.GetString("DirectionsOnMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a download.
        /// </summary>
        public static string DownloadMenuButtonText {
            get {
                return ResourceManager.GetString("DownloadMenuButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a getting location....
        /// </summary>
        public static string GettingLocationProgressText {
            get {
                return ResourceManager.GetString("GettingLocationProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a landmarks off.
        /// </summary>
        public static string LandmarksOffMenuItemText {
            get {
                return ResourceManager.GetString("LandmarksOffMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a landmarks on.
        /// </summary>
        public static string LandmarksOnMenuItemText {
            get {
                return ResourceManager.GetString("LandmarksOnMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a locate me.
        /// </summary>
        public static string LocateMeMenuButtonText {
            get {
                return ResourceManager.GetString("LocateMeMenuButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow.
        /// </summary>
        public static string LocationAllowButtonText {
            get {
                return ResourceManager.GetString("LocationAllowButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string LocationCancelButtonText {
            get {
                return ResourceManager.GetString("LocationCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current location cannot be obtained. Check that location service is turned on in phone settings..
        /// </summary>
        public static string LocationDisabledMessageBoxText {
            get {
                return ResourceManager.GetString("LocationDisabledMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your current location helps us provide you with better exploring experience..
        /// </summary>
        public static string LocationUsageInfoText {
            get {
                return ResourceManager.GetString("LocationUsageInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow map explorer to access and use your.
        /// </summary>
        public static string LocationUsageQueryText {
            get {
                return ResourceManager.GetString("LocationUsageQueryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Allow map explorer to access and use your location?.
        /// </summary>
        public static string LocationUsageQueryText1 {
            get {
                return ResourceManager.GetString("LocationUsageQueryText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a your location.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your current location not available..
        /// </summary>
        public static string NoCurrentLocationMessageBoxText {
            get {
                return ResourceManager.GetString("NoCurrentLocationMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your current location not available..
        /// </summary>
        public static string NoCurrentLocationMessageBoxText1 {
            get {
                return ResourceManager.GetString("NoCurrentLocationMessageBoxText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Location information not found..
        /// </summary>
        public static string NoInfoMessageBoxText {
            get {
                return ResourceManager.GetString("NoInfoMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No match found. Narrow your search e.g. &quot;Seattle Wa&quot;..
        /// </summary>
        public static string NoMatchFoundMessageBoxText {
            get {
                return ResourceManager.GetString("NoMatchFoundMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pedestrian features off.
        /// </summary>
        public static string PedestrianFeaturesOffMenuItemText {
            get {
                return ResourceManager.GetString("PedestrianFeaturesOffMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pedestrian features on.
        /// </summary>
        public static string PedestrianFeaturesOnMenuItemText {
            get {
                return ResourceManager.GetString("PedestrianFeaturesOnMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection1 {
            get {
                return ResourceManager.GetString("ResourceFlowDirection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en-US.
        /// </summary>
        public static string ResourceLanguage1 {
            get {
                return ResourceManager.GetString("ResourceLanguage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a route.
        /// </summary>
        public static string RouteMenuButtonText {
            get {
                return ResourceManager.GetString("RouteMenuButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a searching....
        /// </summary>
        public static string SearchingProgressText {
            get {
                return ResourceManager.GetString("SearchingProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a search.
        /// </summary>
        public static string SearchMenuButtonText {
            get {
                return ResourceManager.GetString("SearchMenuButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a settings.
        /// </summary>
        public static string SettingsMenuButtonText {
            get {
                return ResourceManager.GetString("SettingsMenuButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
    }
}
